# I would like to state upfront that most of this code was generated by Google Gemini. 
# This was my first web-scrapping project and an ambitious one at that. 
# The html structure for a majority of the sites is not beginner friendly.
# The sites seem to have some structural components to stop scrapping.
# Thus, I turned to Gemini to help parse out the CSS selectors and html elements as well as 
# navigate the connection configuration issues for such a large web-scrapping operation.
# While I did not completely write this, I do understand most of it.

# All That aside, I developed this script to help me easily input contact information 
# into an excel spreadsheet for my freelance sport photography business.
# The script inputs a dataset of all 1081 NCAA member schools that I pulled from the NCAA website,
# tries to find the schools staff directory, and scrape the information.

library(tidyverse)
library(rvest)
library(httr)
library(parallelly)
library(writexl)

# --- 1. CONFIGURATION & HELPERS ---
Freelance_Photos_Info_NCAA_Members <- read_csv("data/input/Freelance Photos Info - NCAA Members.csv") #I manually created this csv

target_departments <- "comm|media|relat|mark|creat|video|photo|content|digit|social|graphic|design|sid|art|info|director" #used to filter the larger dataset
safe_read_html     <- possibly(read_html, otherwise = NA)

ncaa_members_staff_parsed <- Freelance_Photos_Info_NCAA_Members |> #cleans up the manually create csv and adds a blanket staff directory url
  separate_wider_delim(cols = Website, delim = "\n", names = c("uni_url", "ath_url"), too_few = "align_start") |> 
  filter(!is.na(ath_url)) |> 
  mutate( 
    short_name = str_remove_all(uni_url, "^www[.]|[.]edu|https://www[.]|[/]$"),
    base_url = str_remove_all(ath_url, "^\\W+|https://www[.]|^https://|^www.|(?<=[.]com|[.]org)\\S+|[/]landing\\S+|index\\S+"),
    base_url = str_remove(base_url, "[/]$"),
    url = str_replace_all(base_url, "^", "https://www."),
    parsed_url = map(url, parse_url),
    hostname = map_chr(parsed_url, "hostname"),
    hostname_url = str_replace_all(hostname, "^", "https://"),
    
    # Check for the exact URL and replace it; otherwise, keep the existing hostname_url
    # This is here for some odd edge cases that the pathway test missed
    hostname_url = case_when(
      hostname_url == "https://www.central.edu"    ~ "https://athletics.central.edu",
      hostname_url == "https://www.greenville.edu" ~ "https://greenvillepanthers.com",
      hostname_url == "https://www.rose-hulman.edu" ~ "https://athletics.rose-hulman.edu",
      hostname_url == "https://www.westminster.edu" ~ "https://athletics.westminster.edu",
      hostname_url == "https://www.whitman.edu" ~ "https://whitmanblues.com",
      hostname_url == "https://www.wofford.edu" ~ "https://woffordterriers.com",
      .default = hostname_url
    ),
    
    staff_directory = str_replace_all(hostname_url, "$", "/staff-directory") # not really necessary, but helpful for me when integrating with the excel sheet
  )

# Bitwise XOR decryption helper for Cloudflare-hidden emails [I don't understand this]
decrypt_cf_email <- function(cipher) {
  if (is.na(cipher) || cipher == "") return(NA_character_)
  tryCatch({
    hex <- str_sub(cipher, 1)
    k <- as.integer(paste0("0x", str_sub(hex, 1, 2)))
    email_bytes <- numeric()
    for (i in seq(3, nchar(hex), by = 2)) {
      b <- as.integer(paste0("0x", str_sub(hex, i, i+1)))
      email_bytes <- c(email_bytes, bitwXor(b, k))
    }
    rawToChar(as.raw(email_bytes))
  }, error = function(e) NA_character_)
}

# --- 2. YOUR V2 EXTRACTION LOGIC (Integrated & Fixed Title Cleaning) --- 
#Most of the NCAA member sites are created by SIDEARMSPORTS and share similar html structures.
#There seems to be two versions that sidearm has and this handles the newer generation.
#This solution is mostly my idea, as Gemini consistently failed to scrape from sidearm V2 sites.
#The function basically pulls the raw html text for each entry/staff member and extracts the contact information using regex patterns.
parse_sidearm_v2_string <- function(html_node) {
  selector <- "#listPanel > div > div.s-person-card__content.flex.flex-wrap.items-center.justify-between.px-\\[32px\\].py-\\[16px\\].md\\:flex-nowrap"
  raw_text <- html_node |> html_elements(selector) |> html_text2()
  
  if (length(raw_text) == 0) return(NULL)
  
  tbl <- tibble(raw = raw_text) |> 
    filter(raw != "" & !is.na(raw))
  
  if (nrow(tbl) == 0) return(NULL)
  
  tbl <- tbl |> 
    separate_wider_delim(cols = raw, delim = "\n", names = c("name", "title"), too_many = "merge") |> 
    mutate(
      phone = str_extract(title, "\\d+[-]\\d+[-]\\d+"),
      email = str_extract(title, "\\S+[@]\\S+"),
      # FIXED: Removed the invalid "string " word from the column assignment
      title = str_remove_all(title, "\\d+[-]\\d+[-]\\d+|\\S+[@]\\S+|Phone") |> str_trim()
    )
  
  return(tbl)
}

# --- 3. MASTER MULTI-PROVIDER ENGINE ---
#The primary function that exractes the staff data
extract_staff_data <- function(html_node) {
  empty_fallback <- tibble(name = character(), title = character(), email = character(), phone = character())
  if (is.na(html_node) || is.null(html_node)) return(empty_fallback)
  
  # Global regex patterns for safe identification and scrubbing
  pronoun_regex <- "(?i)\\s*\\(?(he/him(/his)?|she/her(/hers)?|they/them(/theirs)?)\\)?\\s*"
  phone_regex <- "(?:\\(\\d{3}\\)[\\s.-]*|\\b\\d{3}[\\s.-]+)?\\d{3}[\\s.-]+\\d{4}\\b(?:\\s*\\([a-zA-Z]\\))?"
  
  # Alma Mater, Year, & Title detection for smart column skipping 
  alma_mater_year_regex <- "(?:'|’)\\d{2}\\b|\\b(?:19|20)\\d{2}\\b"
  title_keyword_regex <- "(?i)\\b(coach|director|assistant|coordinator|manager|admin|specialist|head|associate|trainer|operations|athletic|sports|faculty|provost|president|chancellor|compliance|medicine|communications|deputy|executive|chief|leader|officer|general)\b"
  
  # --- STRATEGY A: SIDEARM V2 VIA YOUR INTEGRATED FUNCTION ---
  v2_data <- tryCatch(parse_sidearm_v2_string(html_node), error = function(e) NULL)
  if (!is.null(v2_data) && nrow(v2_data) > 0) {
    v2_data$name <- str_remove_all(v2_data$name, pronoun_regex) |> str_trim()
    v2_data$title <- str_remove_all(v2_data$title, pronoun_regex) |> str_trim()
    return(v2_data)
  }
  
  # --- STRATEGY B: WMT DIGITAL / LIST-BASED DETECTOR ---
  #This is the other main html site structure. This part of the function essentially test for this site structure, pulls the raw text, and pulls contact information using regex matching
  #This orginally pulled the data from using the column number, but I had Gemini essentially reapply my raw text method for the Sidearm V2 sites
  wmt_nodes <- html_node |> html_elements(".wmt-directory ul li, .wmt-staff-item, .staff-directory-item") 
  wmt_nodes <- wmt_nodes[str_detect(html_text2(wmt_nodes), "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b")]
  
  if (length(wmt_nodes) > 0) {
    wmt_data <- map_df(wmt_nodes, function(node) {
      raw_text <- node |> html_text2() |> str_replace_all("\\s+", " ")
      
      email <- str_extract(raw_text, "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b")
      phone <- str_extract(raw_text, phone_regex)
      
      clean_text <- raw_text
      if (!is.na(email)) clean_text <- str_remove(clean_text, fixed(email))
      if (!is.na(phone)) clean_text <- str_remove(clean_text, fixed(phone))
      clean_text <- str_trim(clean_text)
      
      bold_text <- node |> html_element("strong, b") |> html_text2() |> str_trim()
      
      if (!is.na(bold_text) && bold_text != "") {
        title <- bold_text
        name <- str_trim(str_remove(clean_text, fixed(title)))
      } else {
        parts <- str_split(clean_text, " {2,}")[[1]]
        name <- parts[1]
        title <- if(length(parts) > 1) parts[2] else NA_character_
      }
      
      name <- str_remove_all(name, pronoun_regex) |> str_trim()
      if (!is.na(title)) title <- str_remove_all(title, pronoun_regex) |> str_trim()
      
      tibble(name = name, title = title, email = email, phone = phone)
    })
    
    wmt_data <- wmt_data |> filter(!is.na(name) & name != "")
    if (nrow(wmt_data) > 0) return(wmt_data)
  }
  
  # --- STRATEGY C: LEGACY TABLE / ROW TEXT-SPLITTING METHOD ---
  #This is for older versions of sidearm. This tries to pull the data using common sidearm selectors. 
  legacy_selector <- ".sidearm-table-row, tr.sidearm-table-row, .roster-edit-row, .staff-member, .s-person-card, .s-person-details, #main-content article table tbody tr, tr"
  legacy_nodes <- html_node |> html_elements(legacy_selector)
  
  if (length(legacy_nodes) > 0) {
    legacy_data <- map_df(legacy_nodes, function(node) {
      td_elements <- node |> html_elements("td")
      td_texts <- td_elements |> html_text2() |> str_trim()
      name <- NA_character_
      title <- NA_character_
      
      class_name <- node |> html_element(".sidearm-table-player-name, .staff-name, .s-person-card__title") |> html_text2()
      class_title <- node |> html_element(".sidearm-table-player-position, .staff-title, .s-person-card__department, .s-person-card__position") |> html_text2()
      
      if (!is.na(class_name) && class_name != "") {
        name <- class_name
        title <- class_title
      } else if (length(td_texts) >= 2) {#I believe this part is parsing the staff members name when there is a photo. Otherwise it just pulls the name as the class_name
        
        col_idx <- 1 
        first_cell_lower <- str_to_lower(td_texts[1])
        if (td_texts[1] == "" || is.na(td_texts[1]) || str_detect(first_cell_lower, "photo|image|view|select|^[0-9-]+$") || (length(td_texts) >= 3 && nchar(td_texts[1]) <= 2)) {
          col_idx <- 2
        }
        
        name <- td_texts[col_idx]
        col_idx <- col_idx + 1
        
        # ADVANCED LOOKAHEAD: Scan forward past Emails, Phones, Pronouns, or Alma Maters to find the true Title column
        #This was created as a fix where some edge case sites included extra columns for pronouns. Gemini solution was to create this lookahead method
        if (length(td_texts) >= col_idx) {
          
          # Keep scanning forward if the current column looks like noise (email, phone, pronoun, year, or lacking title keywords when next cell has them)
          while (col_idx <= length(td_texts)) {
            curr_val <- td_texts[col_idx]
            curr_cleaned <- str_remove_all(curr_val, pronoun_regex) |> str_trim()
            
            is_noise <- (curr_cleaned == "" ||
                           str_detect(curr_val, "@") ||
                           str_detect(curr_val, phone_regex) ||
                           str_detect(curr_cleaned, alma_mater_year_regex))
            
            # If it doesn't look like noise, check if it contains a title keyword or if we are forced to settle
            if (!is_noise) {
              has_keyword <- str_detect(curr_cleaned, title_keyword_regex)
              # If there's a next column that *does* have a title keyword, keep skipping ahead
              next_has_keyword <- FALSE
              if (col_idx < length(td_texts)) {
                next_cleaned <- str_remove_all(td_texts[col_idx + 1], pronoun_regex) |> str_trim()
                next_has_keyword <- str_detect(next_cleaned, title_keyword_regex)
              }
              
              if (!has_keyword && next_has_keyword) {
                is_noise <- TRUE # Skip this intermediary column (like an email or extra metadata column)
              }
            }
            
            if (is_noise) {
              col_idx <- col_idx + 1
            } else {
              break
            }
          }
          
          title <- if (col_idx <= length(td_texts)) td_texts[col_idx] else NA_character_
        }
      }
      
      if (is.na(name) || name == "") return(NULL)
      
      name <- str_remove_all(name, pronoun_regex) |> str_trim()
      if (!is.na(title)) title <- str_remove_all(title, pronoun_regex) |> str_trim()
      
      email <- NA_character_
      js_script <- node |> html_element("script") |> html_text()
      if (length(js_script) > 0 && !is.na(js_script) && str_detect(js_script, "firstHalf|secondHalf")) {
        first_half <- str_extract(js_script, '(?<=firstHalf\\s?=\\s?[\'"])[^\'"]+')
        second_half <- str_extract(js_script, '(?<=secondHalf\\s?=\\s?[\'"])[^\'"]+')
        if (!is.na(first_half) && !is.na(second_half)) {
          email <- paste0(first_half, "@", second_half)
        }
      }
      
      if (is.na(email)) {
        cf_node <- node |> html_element(".__cf_email__")
        if (length(cf_node) > 0 && !is.na(cf_node)) {
          email <- decrypt_cf_email(html_attr(cf_node, "data-cfemail"))
        }
      }
      
      if (is.na(email)) email <- node |> html_element("a[data-email]") |> html_attr("data-email")
      if (is.na(email)) email <- node |> html_element("a[href^='mailto:']") |> html_attr("href") |> str_remove("^mailto:")
      
      if (is.na(email) && length(td_texts) > 0) {
        email_match <- str_extract(td_texts, "\\w+[@]\\S+")
        email_match <- email_match[!is.na(email_match)]
        email <- if (length(email_match) > 0) head(email_match, 1) else NA_character_
      }
      
      phone <- node |> html_element(".sidearm-table-player-phone, .s-person-card__phone") |> html_text2()
      if (is.na(phone) || phone == "") {
        all_row_text <- node |> html_text2()
        phone <- str_extract(all_row_text, phone_regex)
      }
      
      tibble(name = name, title = title, email = email, phone = phone)
    })
    
    if (nrow(legacy_data) == 0) return(empty_fallback)
    legacy_data <- bind_rows(empty_fallback, legacy_data)
    legacy_data <- legacy_data |> 
      filter(!is.na(name) & name != "") |> 
      filter(!str_to_lower(name) %in% c("name", "staff member", "employee", "position", "photo", "pronouns", "alma mater", "twitter"))
    
    if (nrow(legacy_data) > 0) return(legacy_data)
  }
  
  return(empty_fallback)
}

# --- 4. RUNNING THE PIPELINE (CONNECTION-SAFE METHOD) ---
# --- WATERFALL INTEGRATED PATHWAY PARSER ---
#This is the final function the actually creates the final output.
#It first creates and test common pathways for each staff directory. It also safely configures the connection to pull the data
#It also does some cleaning and extraction as a fall back from the main extraction function
safe_network_parse <- function(base_host_url) {
  if (runif(1) < 0.1) gc()
  empty_fallback <- tibble(name = character(), title = character(), email = character(), phone = character())
  
  # Clean base URL to prevent double slash errors (e.g., http://site.com)
  clean_base <- str_remove(base_host_url, "/+$")
  
  # Define paths, testing both standard and trailing slash configurations
  pathways <- c(
    "/staff-directory/",
    "/staff-directory",
    "/information/directory/index",
    "/staff.aspx",
    "/staff_directory/",
    "/directory/",
    "/staff-directory.aspx",
    "/sports/2017/6/16/michigan-athletics"
  )
  
  for (path in pathways) {
    target_url <- paste0(clean_base, path)
    
    response_obj <- tryCatch({
      httr::GET(
        target_url,
        httr::config(followlocation = TRUE, maxredirs = 5, forbid_reuse = 1),
        httr::add_headers(
          `Connection` = "close",
          `User-Agent` = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        ),
        httr::timeout(15)
      )
    }, error = function(e) NULL)
    
    if (is.null(response_obj)) next
    if (httr::status_code(response_obj) != 200) next
    
    # Extract raw text payload
    payload_text <- tryCatch({
      httr::content(response_obj, as = "text", encoding = "UTF-8")
    }, error = function(e) NULL)
    
    if (is.null(payload_text) || is.na(payload_text) || nchar(payload_text) <= 200) next
    
    # 1. Try structured DOM parsing via your working extract function
    html_tree <- tryCatch(rvest::read_html(payload_text), error = function(e) NULL)
    
    parsed_table <- empty_fallback
    if (!is.null(html_tree)) {
      parsed_table <- tryCatch({
        extract_staff_data(html_tree)
      }, error = function(e) empty_fallback)
    }
    
    # 2. SEED FALLBACK: If DOM structure yields nothing, scrape the raw source text blocks directly
    if (is.null(parsed_table) || nrow(parsed_table) == 0) {
      
      # Extract all email strings found anywhere in the raw HTML payload
      emails <- unique(str_extract_all(payload_text, "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b")[[1]])
      
      # Filter out generic system configuration emails if present
      if (length(emails) > 0) {
        emails <- emails[!str_detect(emails, "wmtdigital|sidearm|pixels|@w3\\.org|example")]
      }
      
      if (length(emails) > 0) {
        # Convert raw HTML source to plain lines to locate text context around emails
        raw_lines <- str_split(payload_text, "[\r\n]+")[[1]] |> str_trim()
        raw_lines <- raw_lines[raw_lines != ""]
        
        parsed_table <- map_df(emails, function(em) {
          # Locate lines containing this email address
          matching_idx <- which(str_detect(raw_lines, fixed(em)))
          if (length(matching_idx) == 0) return(NULL)
          
          # Inspect up to 3 lines above and below the email for name/title clues
          target_idx <- matching_idx[1] # Use first match to prevent array issues
          start_line <- max(1, target_idx - 3)
          end_line <- min(length(raw_lines), target_idx + 3)
          
          context_block <- raw_lines[start_line:end_line] |> 
            paste(collapse = " ") |> 
            str_replace_all("<[^>]*>", " ") |> 
            str_replace_all("\\s+", " ")
          
          # Clean out email and phone patterns to leave name and job title text
          phone <- str_extract(context_block, "\\b\\d{3}[-.]\\d{3}[-.]\\d{4}\\b(?:\\s*\\([a-zA-Z]\\))?")
          
          clean_context <- context_block
          if (!is.na(em)) clean_context <- str_remove(clean_context, fixed(em))
          if (!is.na(phone)) clean_context <- str_remove(clean_context, fixed(phone))
          
          # Clean common structural noise indicators found in script components
          clean_context <- str_remove_all(clean_context, '[\\{\\}\\[\\]\\"\':,;\\-\\*]') |> str_trim()
          
          # Split text fragment into words to isolate Name vs Title components
          words <- str_split(clean_context, "\\s+")[[1]]
          name <- NA_character_
          title <- NA_character_
          
          if (length(words) >= 2) {
            name <- paste(words[1:2], collapse = " ")
            if (length(words) >= 3) {
              title <- paste(words[3:length(words)], collapse = " ")
            }
          } else {
            name <- clean_context
          }
          
          tibble(
            name = as.character(name),
            title = as.character(title),
            email = as.character(em),
            phone = as.character(phone)
          )
        }) 
        
        if (nrow(parsed_table) > 0) {
          parsed_table <- parsed_table |> filter(!is.na(name) & name != "")
        }
      }
    }
    
    # 3. POST-PROCESSING: Handle reversed Name/Title columns before exiting
    if (!is.null(parsed_table) && nrow(parsed_table) > 0) {
      
      # Determine if a column swap is required
      is_calbears <- str_detect(tolower(clean_base), "calbears\\.com")
      
      # Heuristic: Check if 'name' has significantly more title-related keywords than 'title'
      title_regex <- "(?i)\\b(coach|director|assistant|coordinator|manager|admin|specialist|head|associate|trainer|operations)\\b"
      name_col_looks_like_title <- sum(str_detect(parsed_table$name, title_regex), na.rm = TRUE)
      title_col_looks_like_title <- sum(str_detect(parsed_table$title, title_regex), na.rm = TRUE)
      
      # Trigger swap if it's explicitly Cal Bears OR if the heuristic detects reversed data
      needs_swap <- is_calbears || 
        (name_col_looks_like_title > title_col_looks_like_title && 
           name_col_looks_like_title > (nrow(parsed_table) * 0.2))
      
      if (needs_swap) {
        temp_names <- parsed_table$name
        parsed_table$name <- parsed_table$title
        parsed_table$title <- temp_names
      }
      
      return(parsed_table)
    }
  }
  
  return(empty_fallback)
}


#Scrape and Generate Composite Staff Directory of All NCAA Members
full_staff_directory <- ncaa_members_staff_parsed |> 
  mutate(parsed_data = map(hostname_url, safe_network_parse, .progress = "Waterfall & Staff Scraping Info")) |> 
  unnest(parsed_data, keep_empty = TRUE)

#Broad Filtering for Communications and Creative Staff
comms_staff_directory <-  full_staff_directory |> 
  filter(
    is.na(name) | (
      (str_detect(replace_na(str_to_lower(title), ""), target_departments) | 
         str_detect(replace_na(str_to_lower(email), ""), "comm|mark")) & 
        !str_detect(replace_na(str_to_lower(title), ""), "complian|community")
    )
  )

# Explicit final safety sweep to close any hanging OS level descriptors
closeAllConnections()
    
#Function to find schools that were dropped during scraping [I did fully write this]
find_missing <- function(df, source_df){ 
  ref_tbl <- {{ source_df }} |> 
    group_by(short_name) |> 
    summarise()
  
  summarised_df <- {{ df }} |> 
    group_by(short_name) |> 
    summarise()
  
  missing <- anti_join(ref_tbl, summarised_df)
  print(missing)
}

missing_schools <- find_missing(full_staff_directory, ncaa_members_staff_parsed)

#Find Sports Overview/Assignment if any. Needed for Excel/Google Sheets to populate information automatically
comms_staff_directory <- comms_staff_directory |> 
  mutate(
    # FIX 1: Clean the name string outside the Sport_Flags tibble block
    name = str_remove(name, "\\[.*?\\]"),
    
    # 1. Create a data frame column containing ONLY logical sport flags [I mostly wrote this]
    #These flag help further filter the directory for the excel dropdown where I input my contact information
    Sport_Flags = tibble(
      BAD = str_detect(title, regex("badminton", ignore_case = TRUE)),
      BASE = str_detect(title, "Baseball|BASE|\\sBB|\\sBSB"),
      BOWL = str_detect(title, "BOWL|Bowling"),
      BVB = str_detect(title, "Beach Volleyball|BVB"),
      CHEER = str_detect(title, "Cheerleading"),
      CRKT = str_detect(title, "Cricket|cricket"),
      EQU = str_detect(title, "EQ|Equestrian|equestrian"),
      FB = str_detect(title, "Football|FB"),
      FENCE = str_detect(title, "Fencing|FEN"),
      FH = str_detect(title, "Field Hockey|FH"),
      GYM = str_detect(title, "Gymnastics|GYM"),
      HAND = str_detect(title, "Handball"),
      ISKATE = str_detect(title, "Ice Skating"),
      JUDO = str_detect(title, "Judo"),
      LCREW = str_detect(title, "Lightweight Crew"),
      LFB = str_detect(title, "Lightweight Football"),
      ARCH = str_detect(title, "Archery"),
      MBB = str_detect(title, "(?<![Ww]omen's\\s)[Bb]asketball|MBB|M Basketball"),
      MCHEER = str_detect(title, "Men's Cheerleading|M Cheerleading"),
      CREW = str_detect(title, "Crew"),
      MGOLF = str_detect(title, "Men's Golf|MGOLF|\\sGOLF|M Golf"),
      MGYM = str_detect(title, "Men's Gymnastics|M Gymnastics"),
      IH = str_detect(title, "Men's Ice Hockey|Women's Ice Hockey|\\sMIH|IH|Ice Hockey|\\sWIH"),
      MLAX = str_detect(title, "(?<![Ww]omen's\\s)[Ll]acrosse|Men's Lacrosse|MLAX|M Lacrosse|\\sLAX"),
      MSOC = str_detect(title, "(?<![Ww]omen's\\s)[Ss]occer|Men's Soccer|MSOC|\\sSOC|SCCR"),
      MTEN = str_detect(title, "(?<![Ww]omen's\\s)[Tt]ennis|Men's Tennis|MTEN|\\sTEN"),
      MVB = str_detect(title, "Men's Volleyball|MVB|M Volleyball|\\sVB"),
      PIST = str_detect(title, "Pistol"),
      POLO = str_detect(title, "Polo"),
      RDO = str_detect(title, "Rodeo"),
      RIFL = str_detect(title, "Rifle|RIFLE"),
      ROW = str_detect(title, "Rowing|ROW"),
      RUG = str_detect(title, "Rugby"),
      SAIL = str_detect(title, "Sailing|SAIL"),
      SB = str_detect(title, "Softball|SB|SBALL"),
      SKI = str_detect(title, "Skiing|SKI"),
      SPSB = str_detect(title, "Soft Pitch Softball|SPSB"),
      SQSH = str_detect(title, "Squash"),
      SWIM = str_detect(title, "SWIM|[Ss]wimming [&] [Dd]iving|[Ss]wim [&] [Dd]ive|\\sSD|S/D"),
      TRACK = str_detect(title, "[Tt]rack [&] [Ff]ield|T[&]F|TRACK|\\sMT|\\sWT"),
      TRI = str_detect(title, "Triathalon"),
      VB = str_detect(title, "(?<!Men's\\s|Women's\\s|M\\s|W\\s)(Volleyball|VB)"), # Prevent overlap
      WBB = str_detect(title, "(?<![Mm]en's\\s)[Bb]asketball|Women's Basketball|WBB|W Basketball"),
      WGOLF = str_detect(title, "Women's Golf|WGOLF|W Golf"),                        # Fixed Men's typo
      WLAX = str_detect(title, "(?<![Mm]en's\\s)[Ll]acrosse|Women's Lacrosse|WLAX|W Lacrosse|\\sLAX"),
      WP = str_detect(title, "Water Polo|WP"),
      WREST = str_detect(title, "Wrestling|WREST"),
      WSK = str_detect(title, "Water Skiing|WS"),
      WSOC = str_detect(title, "(?<![Mm]en's\\s)[Ss]occer|Women's Soccer|WSOC|\\sSOC|SCCR"),
      WTEN = str_detect(title, "(?<![Mm]en's\\s)[Tt]ennis|Women's Tennis|WTEN|\\sTEN"),
      XC = str_detect(title, "Cross Country|XC")
    ),
    
    # 2. Return a collapsed character string row-by-row
    Sport = pmap_chr(Sport_Flags, function(...) {
      flags <- c(...)
      flags[is.na(flags)] <- FALSE
      
      # FIX 2: Since flags are now guaranteed logical, names indexing works perfectly
      matched_sports <- names(flags)[flags]
      
      if (length(matched_sports) == 0) {
        return(NA_character_)
      } else {
        return(str_c(matched_sports, collapse = ", "))
      }
    })
  ) |> 
  select(-Sport_Flags) |> 
  distinct()

# Filter Directory for SIDs and DPs or equivalent
# My contact is usually directed to the sports information director or director of photography/similar position who typically deals with and hires freelancers
final_comms_staff_directory <- comms_staff_directory |> 
  filter(
    # Keep specific high-priority creative/comms keywords regardless of coaching titles
    (str_detect(title, "(?i)\\bSID\\b|(?i)\\bAD\\b|Supervisor|Athletics? Director|Director of Athletics?|\\b(?:media|public|external)\\srelations\\b|External Operations|Photography|Head Athletics Photographer|(?<!Assistant\\s)Sports Information(?!\\sAssistant)|Director of Creative Content|Director of Creative Services|Communication| Marketing [&] Info") & 
       !str_detect(title, "(?i)Graduate Assistant|Student|Intern")) |
      
      # Otherwise, apply your standard filtering rules
      # Added 'relations' to the end of this list to filter out the ones that didn't match the top regex!
      (!is.na(Sport) & !str_detect(title, "(?i)Quart|Sports Medicine|Partnership|Learning|Photographer|Coach|Trainer|Recruiting|Designer|Advancment|Development|Engagement|Technology|relations"))
  ) |> 
  select(Name:State, short_name, staff_directory:Sport)

#Find missing schools that were filtered out
filtered_out_schools <- anti_join(comms_staff_directory, final_comms_staff_directory, by = "short_name")
filtered_out_schools <- filtered_out_schools |> 
  filter(!if_all(name:Sport, ~ .x == "NA")) |> 
  group_by(short_name) |> 
  summarise(.groups = "drop") |> 
  arrange(short_name, .locale = "en")

write_xlsx(final_comms_staff_directory, "data/ouput/filtered_contacts.xlsx")


ncaa_members_parsed <- ncaa_members_staff_parsed |> 
  select(Name:State, hostname_url, staff_directory)
write_xlsx(ncaa_members_parsed, "data/ouput/ncaa_members.xlsx")

